/**
 * Development seed.
 *
 * Wipes and rebuilds the whole dataset, so it is safe to re-run. Brackets
 * are generated by the real functions in src/lib/brackets.ts rather than
 * hand-written, which makes the seed double as a correctness check.
 */

import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { generateBracket } from "../src/lib/brackets";

const prisma = new PrismaClient();

const GAMES = [
  {
    slug: "ashfall-protocol",
    name: "Ashfall Protocol",
    shortName: "Ashfall",
    genre: "Tactical shooter",
    teamSize: 5,
    roles: ["Breach", "Anchor", "Recon", "Support", "Duelist"],
    rankTiers: ["Copper", "Iron", "Bronze", "Silver", "Gold", "Platinum", "Diamond", "Ascendant", "Apex"],
  },
  {
    slug: "riftbound",
    name: "Riftbound",
    shortName: "Riftbound",
    genre: "MOBA",
    teamSize: 5,
    roles: ["Vanguard", "Jungle", "Mid", "Carry", "Warden"],
    rankTiers: ["Wood", "Bronze", "Silver", "Gold", "Emerald", "Master", "Grandmaster", "Sovereign"],
  },
  {
    slug: "null-sector",
    name: "Null Sector",
    shortName: "Null",
    genre: "Extraction shooter",
    teamSize: 3,
    roles: ["Point", "Tech", "Overwatch"],
    rankTiers: ["Scav", "Runner", "Operator", "Specialist", "Ghost", "Phantom"],
  },
  {
    slug: "overclock-royale",
    name: "Overclock Royale",
    shortName: "Overclock",
    genre: "Battle royale",
    teamSize: 4,
    roles: ["Scout", "Fragger", "Support", "IGL"],
    rankTiers: ["Rookie", "Amateur", "Pro", "Elite", "Champion", "Overclocked"],
  },
  {
    slug: "kite-and-cinder",
    name: "Kite & Cinder",
    shortName: "K&C",
    genre: "Fighting",
    teamSize: 1,
    roles: ["Rushdown", "Zoner", "Grappler"],
    rankTiers: ["Ash", "Ember", "Flare", "Blaze", "Inferno", "Solar"],
  },
  {
    slug: "deepvault",
    name: "Deepvault",
    shortName: "Deepvault",
    genre: "Co-op raid",
    teamSize: 4,
    roles: ["Breaker", "Medic", "Engineer", "Scout"],
    rankTiers: ["Depth I", "Depth II", "Depth III", "Depth IV", "Abyssal"],
  },
];

const PEOPLE = [
  ["kestrelvane", "Kestrel Vane", "SEA", ["en", "th"]],
  ["orbitdecay", "Orbit Decay", "SEA", ["en"]],
  ["mothlight", "Mothlight", "SEA", ["en", "id"]],
  ["nullsix", "Nullsix", "SEA", ["en"]],
  ["brambleknight", "Bramble Knight", "EU West", ["en", "de"]],
  ["ferrofluid", "Ferrofluid", "EU West", ["en", "fr"]],
  ["saltmarsh", "Saltmarsh", "EU West", ["en"]],
  ["quietkiln", "Quiet Kiln", "EU East", ["en"]],
  ["harrowgate", "Harrowgate", "NA East", ["en"]],
  ["vermilionsky", "Vermilion Sky", "NA East", ["en", "es"]],
  ["longwinter", "Long Winter", "NA West", ["en"]],
  ["cobaltmirror", "Cobalt Mirror", "NA West", ["en"]],
  ["duskrunner", "Duskrunner", "SEA", ["en", "th"]],
  ["paperwasp", "Paper Wasp", "SEA", ["en"]],
  ["ironhymn", "Iron Hymn", "OCE", ["en"]],
  ["glasshour", "Glass Hour", "OCE", ["en"]],
  ["tenderthorn", "Tenderthorn", "KR", ["ko", "en"]],
  ["halfstep", "Halfstep", "KR", ["ko"]],
  ["marrowlight", "Marrowlight", "JP", ["ja", "en"]],
  ["sablecrest", "Sablecrest", "JP", ["ja"]],
  ["hollowpine", "Hollowpine", "EU West", ["en"]],
  ["cinderpath", "Cinderpath", "SEA", ["en", "id"]],
  ["ninthward", "Ninth Ward", "NA East", ["en"]],
  ["fadeaway", "Fadeaway", "NA West", ["en", "es"]],
] as const;

const TEAMS = [
  ["nova-drift", "Nova Drift", "NOVA", "SEA", "ashfall-protocol"],
  ["zero-parallax", "Zero Parallax", "ZRP", "SEA", "ashfall-protocol"],
  ["quiet-storm", "Quiet Storm", "QST", "EU West", "ashfall-protocol"],
  ["black-sundial", "Black Sundial", "BSD", "EU West", "ashfall-protocol"],
  ["helix-nine", "Helix Nine", "HX9", "NA East", "ashfall-protocol"],
  ["carrion-club", "Carrion Club", "CARR", "NA West", "ashfall-protocol"],
  ["lantern-guard", "Lantern Guard", "LTG", "OCE", "ashfall-protocol"],
  ["static-choir", "Static Choir", "STC", "KR", "ashfall-protocol"],
  ["paper-lantern", "Paper Lantern", "PLN", "SEA", "riftbound"],
  ["gravewell", "Gravewell", "GRV", "EU West", "riftbound"],
  ["copperline", "Copperline", "CPR", "NA East", "riftbound"],
  ["tidebreak", "Tidebreak", "TIDE", "JP", "riftbound"],
] as const;

const CHAT_LINES = [
  "no way he holds that angle",
  "run it back",
  "who taught him that lineup",
  "chat is coping",
  "that was actually clean",
  "chat vote: push or rotate",
  "chat needs a slow mode already",
  "chat: he's cooking",
  "aim check please",
  "GG",
  "how many hours does this guy have",
  "second time this week he pulls that",
  "worth the sub",
  "queue with us after?",
  "put that in a clip",
];

const rnd = (max: number) => Math.floor(Math.random() * max);
const pick = <T,>(list: readonly T[]) => list[rnd(list.length)];
const daysAgo = (days: number) => new Date(Date.now() - days * 864e5);

async function wipe() {
  const order = [
    prisma.predictionEntry,
    prisma.pollOption,
    prisma.poll,
    prisma.communityPoint,
    prisma.voiceParticipant,
    prisma.voiceRoom,
    prisma.communityPost,
    prisma.communityChannel,
    prisma.communityMember,
    prisma.community,
    prisma.matchResult,
    prisma.tournamentMatch,
    prisma.tournamentTeam,
    prisma.tournamentRegistration,
    prisma.tournament,
    prisma.teamOpening,
    prisma.teamMember,
    prisma.teamGame,
    prisma.team,
    prisma.reaction,
    prisma.comment,
    prisma.clip,
    prisma.vOD,
    prisma.streamSession,
    prisma.chatMessage,
    prisma.stream,
    prisma.subscription,
    prisma.lFGPost,
    prisma.message,
    prisma.conversationMember,
    prisma.conversation,
    prisma.notification,
    prisma.userAchievement,
    prisma.achievement,
    prisma.report,
    prisma.ban,
    prisma.friendship,
    prisma.follow,
    prisma.gameRank,
    prisma.playerPreference,
    prisma.session,
    prisma.profile,
    prisma.user,
    prisma.game,
  ];
  for (const table of order) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (table as any).deleteMany();
  }
}

async function main() {
  console.log("Clearing existing data…");
  await wipe();

  console.log("Games…");
  const games = await Promise.all(
    GAMES.map((game) =>
      prisma.game.create({
        data: {
          slug: game.slug,
          name: game.name,
          shortName: game.shortName,
          genre: game.genre,
          teamSize: game.teamSize,
          roles: [...game.roles],
          rankTiers: [...game.rankTiers],
        },
      }),
    ),
  );
  const gameBySlug = Object.fromEntries(games.map((game) => [game.slug, game]));

  console.log("People…");
  const passwordHash = await bcrypt.hash("password123", 12);

  const demo = await prisma.user.create({
    data: {
      email: "demo@holdpoint.gg",
      username: "demo",
      displayName: "Demo Player",
      passwordHash,
      // ADMIN rather than CREATOR — this is the account the README tells
      // people to log in with, and without at least one ADMIN a fresh seed
      // would leave /admin/users unreachable by anyone.
      role: "ADMIN",
      presence: "ONLINE",
      onboardedAt: daysAgo(40),
      profile: {
        create: {
          bio: "Ashfall main, occasional Riftbound support. Scrims most weeknights, tournaments most weekends.",
          region: "SEA",
          languages: ["en", "th"],
          level: 34,
          xp: 96_500,
          verified: true,
        },
      },
      preference: {
        create: {
          region: "SEA",
          languages: ["en", "th"],
          platforms: ["PC"],
          competitive: 72,
          micRequired: true,
          activeHours: [19, 20, 21, 22, 23],
          goals: ["TEAMMATES", "TOURNAMENTS", "WATCH"],
          preferredRoles: ["Anchor", "Warden"],
        },
      },
    },
  });

  const users = await Promise.all(
    PEOPLE.map(([username, displayName, region, languages], index) =>
      prisma.user.create({
        data: {
          email: `${username}@holdpoint.gg`,
          username,
          displayName,
          passwordHash,
          role: index < 8 ? "CREATOR" : index === 23 ? "MODERATOR" : "VIEWER",
          presence: (["ONLINE", "IN_GAME", "STREAMING", "AWAY", "OFFLINE"] as const)[index % 5],
          onboardedAt: daysAgo(60 - index),
          profile: {
            create: {
              bio:
                index % 3 === 0
                  ? "Ranked grinder. Voice comms on, ego off."
                  : index % 3 === 1
                    ? "Streams most nights. Clips get posted the morning after."
                    : "Coach and analyst. Happy to review VODs for anyone in the community.",
              region,
              languages: [...languages],
              level: 4 + index * 3,
              xp: 400 + index * 4200,
              verified: index < 5,
            },
          },
          preference: {
            create: {
              region,
              languages: [...languages],
              platforms: index % 4 === 0 ? ["PC", "PS5"] : ["PC"],
              competitive: 25 + ((index * 13) % 70),
              micRequired: index % 5 !== 0,
              activeHours: index % 2 === 0 ? [19, 20, 21, 22, 23] : [13, 14, 15, 20, 21],
              goals: index % 2 === 0 ? ["TEAMMATES", "TOURNAMENTS"] : ["WATCH", "COMMUNITY"],
              preferredRoles: [
                pick(GAMES[0].roles),
                ...(index % 3 === 0 ? [pick(GAMES[1].roles)] : []),
              ],
            },
          },
        },
      }),
    ),
  );
  const everyone = [demo, ...users];

  console.log("Ranks…");
  for (const user of everyone) {
    const chosen = [GAMES[0], GAMES[(everyone.indexOf(user) % 5) + 1]];
    for (const game of chosen) {
      const tierIdx = 2 + rnd(game.rankTiers.length - 3);
      await prisma.gameRank.create({
        data: {
          userId: user.id,
          gameId: gameBySlug[game.slug].id,
          tier: game.rankTiers[tierIdx],
          tierIdx,
          role: pick(game.roles),
          hours: 120 + rnd(1800),
          verified: Math.random() > 0.6,
        },
      });
    }
  }

  console.log("Channels…");
  const creators = users.slice(0, 9);
  const streams = await Promise.all(
    creators.map((creator, index) => {
      const game = games[index % games.length];
      const isLive = index < 5;
      return prisma.stream.create({
        data: {
          userId: creator.id,
          slug: creator.username,
          title: [
            "Ranked climb to Apex — day 9",
            "Scrim block with Nova Drift, then chill ranked",
            "Coaching viewers' VODs until the queue dies",
            "Qualifier day. Win and we're in.",
            "New patch, new lineups. Testing everything.",
            "Late night duo queue",
            "Community game night — join the lobby",
            "Reviewing the grand final round by round",
            "Casual raids, chat picks the loadout",
          ][index],
          gameId: game.id,
          tags: [
            ["Ranked", "English"],
            ["Scrims", "Competitive"],
            ["Coaching", "Chill"],
            ["Tournament", "Qualifier"],
            ["Patch notes", "Testing"],
          ][index % 5],
          language: creator.username === "tenderthorn" ? "ko" : "en",
          isLive,
          viewerCount: isLive ? 340 + rnd(14_000) : 0,
          peakViewers: 2_000 + rnd(19_000),
          startedAt: isLive ? new Date(Date.now() - (20 + rnd(180)) * 60_000) : null,
          streamKey: `live_${creator.username}_${rnd(999_999)}`,
          chatSlowMode: index === 1 ? 3 : 0,
          followersOnly: index === 3,
        },
      });
    }),
  );

  console.log("Follows and subscriptions…");
  for (const stream of streams) {
    await prisma.follow.create({
      data: { followerId: demo.id, followedId: stream.userId },
    });
    for (const user of users.slice(6, 6 + 10 + rnd(8))) {
      if (user.id === stream.userId) continue;
      await prisma.follow.create({
        data: { followerId: user.id, followedId: stream.userId },
      });
    }
  }
  for (const stream of streams.slice(0, 4)) {
    for (const user of users.slice(10, 15)) {
      await prisma.subscription.create({
        data: {
          creatorId: stream.userId,
          viewerId: user.id,
          tier: pick(["TIER_1", "TIER_1", "TIER_2", "TIER_3"] as const),
          renewsAt: new Date(Date.now() + 20 * 864e5),
        },
      });
    }
  }

  console.log("Chat, sessions and VODs…");
  for (const stream of streams) {
    if (stream.isLive) {
      for (let i = 0; i < 26; i++) {
        const author = pick(users);
        await prisma.chatMessage.create({
          data: {
            streamId: stream.id,
            userId: author.id,
            body: pick(CHAT_LINES),
            pinned: i === 0,
            createdAt: new Date(Date.now() - (26 - i) * 9_000),
          },
        });
      }
      await prisma.poll.create({
        data: {
          streamId: stream.id,
          kind: "PREDICTION",
          question: "Do we win the next map?",
          closesAt: new Date(Date.now() + 15 * 60_000),
          options: {
            create: [
              { label: "We take it", votes: 480 + rnd(900), points: 12_000 + rnd(40_000) },
              { label: "We drop it", votes: 120 + rnd(500), points: 4_000 + rnd(18_000) },
            ],
          },
        },
      });
    }

    for (let s = 0; s < 8; s++) {
      const session = await prisma.streamSession.create({
        data: {
          streamId: stream.id,
          gameId: stream.gameId,
          title: `Session ${8 - s}`,
          startedAt: daysAgo(s + 1),
          endedAt: new Date(daysAgo(s + 1).getTime() + (3 + rnd(4)) * 3600_000),
          peakViewers: 900 + rnd(9_000),
          avgViewers: 400 + rnd(4_000),
          minutesWatched: 20_000 + rnd(180_000),
          followersGained: 20 + rnd(400),
        },
      });
      if (s < 4) {
        await prisma.vOD.create({
          data: {
            streamId: stream.id,
            sessionId: session.id,
            userId: stream.userId,
            gameId: stream.gameId,
            title: `${stream.title} — part ${4 - s}`,
            durationSec: 3600 * (2 + rnd(3)),
            views: 1_200 + rnd(60_000),
            createdAt: daysAgo(s + 1),
          },
        });
      }
    }
  }

  // Deliberately no fake Clip rows here: ClipStage's generated-art
  // fallback (a gradient Thumb plus a play-button placeholder, for a clip
  // with no playbackUrl) exists so a real clip still renders something
  // reasonable if its video is ever unreachable — it was never meant to
  // be the seed data's stand-in for "we don't have a video file to seed
  // with." Seeding a Clip row without one just means every clip in a
  // fresh feed is that placeholder. Upload a real clip through the app
  // (/clips/new) instead — see scripts/delete-clips-without-video.ts for
  // clearing out any of the old placeholder rows a previous seed left
  // behind.

  console.log("Communities…");
  const communities = [
    {
      slug: "ashfall-sea",
      name: "Ashfall SEA",
      tagline: "Ranked, scrims and roster hunting across Southeast Asia",
      description:
        "The largest Ashfall room in the region. Scrim blocks Tuesday and Thursday, open ranked lobbies every night.",
      game: "ashfall-protocol",
    },
    {
      slug: "night-shift",
      name: "Night Shift",
      tagline: "For people who queue after midnight",
      description:
        "No rank requirement, no ego. Mostly Riftbound and Overclock, mostly after 1am local.",
      game: "riftbound",
    },
    {
      slug: "vault-crew",
      name: "Vault Crew",
      tagline: "Deepvault raids, every weekend",
      description: "Weekly raid nights, loadout theorycrafting and a very patient teaching channel.",
      game: "deepvault",
    },
    {
      slug: "the-corner",
      name: "The Corner",
      tagline: "Fighting game locals, online",
      description: "Weekly Kite & Cinder brackets, matchup notes and frame data arguments.",
      game: "kite-and-cinder",
    },
  ];

  for (const entry of communities) {
    const community = await prisma.community.create({
      data: {
        slug: entry.slug,
        name: entry.name,
        tagline: entry.tagline,
        description: entry.description,
        gameId: gameBySlug[entry.game].id,
        memberCount: 400 + rnd(9_000),
        channels: {
          create: [
            { name: "announcements", kind: "ANNOUNCEMENT", position: 0, topic: "Read-only. Events and rule changes." },
            { name: "general", kind: "TEXT", position: 1, topic: "Anything goes, keep it civil." },
            { name: "looking-for-team", kind: "TEXT", position: 2, topic: "Post rank, role, region and hours." },
            { name: "clips", kind: "CLIPS", position: 3 },
            { name: "ranked", kind: "TEXT", position: 4 },
            { name: "tournament-talk", kind: "TEXT", position: 5 },
          ],
        },
        voiceRooms: {
          create: [
            { name: "Queue up", capacity: 10 },
            { name: "Scrim room", capacity: 12 },
          ],
        },
      },
      include: { channels: true, voiceRooms: true },
    });

    const members = [demo, ...users.slice(0, 12 + rnd(8))];
    for (const member of members) {
      await prisma.communityMember.create({
        data: {
          communityId: community.id,
          userId: member.id,
          role: member.id === users[0].id ? "OWNER" : member.id === users[3].id ? "MODERATOR" : "MEMBER",
          points: rnd(4_000),
        },
      });
    }

    const posts = [
      "Scrim block moved to 21:00 tonight — the other org double-booked.",
      "Reminder: post your rank AND your hours in looking-for-team, not just your rank.",
      "We have two spots open for the Saturday bracket if anyone's roster is short.",
      "Anyone else getting packet loss on the SEA servers since the patch?",
      "VOD review at the weekend. Drop your worst round, not your best one.",
      "New rule: no recruiting in general, use the right channel please.",
    ];
    for (const channel of community.channels.slice(0, 3)) {
      for (let i = 0; i < 4; i++) {
        await prisma.communityPost.create({
          data: {
            channelId: channel.id,
            authorId: pick(members).id,
            body: pick(posts),
            pinned: i === 0 && channel.kind === "ANNOUNCEMENT",
            createdAt: new Date(Date.now() - (i + 1) * 3600_000 * (1 + rnd(20))),
          },
        });
      }
    }

    for (const room of community.voiceRooms.slice(0, 1)) {
      for (const participant of users.slice(0, 3 + rnd(3))) {
        await prisma.voiceParticipant.create({
          data: {
            roomId: room.id,
            userId: participant.id,
            speaking: Math.random() > 0.6,
            muted: Math.random() > 0.7,
          },
        });
      }
    }
  }

  console.log("Teams…");
  const teams = [];
  for (const [slug, name, tag, region, gameSlug] of TEAMS) {
    const game = gameBySlug[gameSlug];
    const roster = [...users].sort(() => Math.random() - 0.5).slice(0, game.teamSize);
    const team = await prisma.team.create({
      data: {
        slug,
        name,
        tag,
        region,
        ownerId: roster[0].id,
        logoSeed: slug,
        description: `${region} ${game.shortName} roster. Scrims most weeknights, competes in regional qualifiers.`,
        wins: 4 + rnd(22),
        losses: rnd(14),
        games: { create: { gameId: game.id } },
        members: {
          create: roster.map((member, index) => ({
            userId: member.id,
            role: index === 0 ? "OWNER" : index === 1 ? "CAPTAIN" : "PLAYER",
            position: game.roles[index % game.roles.length],
          })),
        },
      },
    });
    teams.push(team);
  }

  // Demo player is rostered on the first team so the "your teams" state is real.
  await prisma.teamMember.create({
    data: { teamId: teams[0].id, userId: demo.id, role: "CAPTAIN", position: "Anchor" },
  });

  for (const team of teams.slice(0, 5)) {
    await prisma.teamOpening.create({
      data: {
        teamId: team.id,
        position: pick(GAMES[0].roles),
        minTier: "Diamond",
        region: team.region,
        availability: "Weeknights 20:00–24:00",
      },
    });
  }

  console.log("Tournaments and brackets…");
  const ashfallTeams = teams.filter((team) => team.slug !== "paper-lantern").slice(0, 8);
  const riftTeams = teams.slice(8, 12);

  const specs = [
    {
      slug: "ashfall-open-qualifier-3",
      name: "Ashfall Open Qualifier #3",
      format: "SINGLE_ELIMINATION" as const,
      game: "ashfall-protocol",
      status: "LIVE" as const,
      entrants: ashfallTeams,
      prize: 5_000,
      played: true,
    },
    {
      slug: "midnight-circuit-s2",
      name: "Midnight Circuit S2",
      format: "DOUBLE_ELIMINATION" as const,
      game: "ashfall-protocol",
      status: "REGISTRATION_OPEN" as const,
      entrants: ashfallTeams.slice(0, 4),
      prize: 12_000,
      played: false,
    },
    {
      slug: "riftbound-round-table",
      name: "Riftbound Round Table",
      format: "ROUND_ROBIN" as const,
      game: "riftbound",
      status: "LIVE" as const,
      entrants: riftTeams,
      prize: 2_500,
      played: true,
    },
  ];

  for (const spec of specs) {
    const tournament = await prisma.tournament.create({
      data: {
        slug: spec.slug,
        name: spec.name,
        organizerId: spec.status === "LIVE" ? users[0].id : demo.id,
        gameId: gameBySlug[spec.game].id,
        description:
          "Open registration, single roster per organisation, rosters lock at the registration deadline.",
        region: "SEA",
        format: spec.format,
        teamSize: gameBySlug[spec.game].teamSize,
        maxTeams: spec.format === "ROUND_ROBIN" ? 4 : 8,
        status: spec.status,
        registrationOpensAt: daysAgo(14),
        registrationClosesAt: spec.status === "LIVE" ? daysAgo(2) : new Date(Date.now() + 6 * 864e5),
        startsAt: spec.status === "LIVE" ? daysAgo(1) : new Date(Date.now() + 9 * 864e5),
        prizePool: spec.prize,
        entryFee: 0,
        rules: [
          "Rosters lock when registration closes. Substitutes must be declared before the first match.",
          "Best of one until the semi-finals, best of three from there.",
          "Both captains report the score. A mismatch opens a dispute for the organiser.",
          "No stream sniping. Delay is enforced on the main broadcast.",
        ].join("\n\n"),
      },
    });

    const entries = await Promise.all(
      spec.entrants.map((team, index) =>
        prisma.tournamentTeam.create({
          data: { tournamentId: tournament.id, teamId: team.id, seed: index + 1 },
        }),
      ),
    );
    for (const team of spec.entrants) {
      await prisma.tournamentRegistration.create({
        data: { tournamentId: tournament.id, teamId: team.id, status: "APPROVED", roster: [] },
      });
    }

    const seedToTeam = new Map(entries.map((entry) => [entry.seed, entry.teamId]));
    const specMatches = generateBracket(spec.format, spec.entrants.length);
    const idByKey = new Map<string, string>();

    for (const match of specMatches) {
      const created = await prisma.tournamentMatch.create({
        data: {
          tournamentId: tournament.id,
          side: match.side,
          round: match.round,
          position: match.position,
          homeTeamId: match.homeSeed ? seedToTeam.get(match.homeSeed) ?? null : null,
          awayTeamId: match.awaySeed ? seedToTeam.get(match.awaySeed) ?? null : null,
          state: match.isBye ? "BYE" : "PENDING",
          scheduledAt: new Date(Date.now() + match.round * 3600_000),
        },
      });
      idByKey.set(match.key, created.id);
    }
    for (const match of specMatches) {
      if (!match.winnerNext && !match.loserNext) continue;
      await prisma.tournamentMatch.update({
        where: { id: idByKey.get(match.key)! },
        data: {
          winnerNextId: match.winnerNext ? idByKey.get(match.winnerNext) : null,
          loserNextId: match.loserNext ? idByKey.get(match.loserNext) : null,
        },
      });
    }

    if (spec.played) {
      // Play out the first round for real, so the bracket has genuine state.
      const first = await prisma.tournamentMatch.findMany({
        where: { tournamentId: tournament.id, round: 1 },
        orderBy: { position: "asc" },
      });
      for (const [index, match] of first.entries()) {
        if (!match.homeTeamId || !match.awayTeamId) continue;
        const isLive = index === first.length - 1;
        const homeWins = index % 3 !== 2;
        // A LIVE match is still being played, so it can't carry a decided
        // scoreline — only completed matches get the final 2-1/1-2 result.
        const homeScore = isLive ? 0 : homeWins ? 2 : 1;
        const awayScore = isLive ? 0 : homeWins ? 1 : 2;
        await prisma.tournamentMatch.update({
          where: { id: match.id },
          data: { homeScore, awayScore, state: isLive ? "LIVE" : "COMPLETED" },
        });
        if (isLive) continue;

        const winnerTeamId = homeWins ? match.homeTeamId : match.awayTeamId;
        const loserTeamId = homeWins ? match.awayTeamId : match.homeTeamId;

        await prisma.matchResult.create({
          data: {
            matchId: match.id,
            winnerTeamId,
            homeScore,
            awayScore,
            reportedById: demo.id,
            confirmedById: users[1].id,
          },
        });

        // Round robin standings live on `points`; wins/losses and elimination
        // only apply to the bracket formats.
        await prisma.tournamentTeam.update({
          where: { tournamentId_teamId: { tournamentId: tournament.id, teamId: winnerTeamId } },
          data: { wins: { increment: 1 } },
        });
        await prisma.tournamentTeam.update({
          where: { tournamentId_teamId: { tournamentId: tournament.id, teamId: loserTeamId } },
          data: {
            losses: { increment: 1 },
            ...(spec.format === "ROUND_ROBIN" ? {} : { eliminated: true }),
          },
        });
        await prisma.team.update({ where: { id: winnerTeamId }, data: { wins: { increment: 1 } } });
        await prisma.team.update({ where: { id: loserTeamId }, data: { losses: { increment: 1 } } });

        if (match.winnerNextId) {
          const next = await prisma.tournamentMatch.findUnique({ where: { id: match.winnerNextId } });
          await prisma.tournamentMatch.update({
            where: { id: match.winnerNextId },
            data: next?.homeTeamId ? { awayTeamId: winnerTeamId } : { homeTeamId: winnerTeamId },
          });
        }
      }
    }
  }

  console.log("LFG, messages, achievements, notifications…");
  const lfgBodies = [
    "Diamond Anchor looking for two for ranked tonight, 21:00 SEA onwards.",
    "Building a Riftbound roster for the next open circuit. Need a Warden and a Jungle, Emerald+.",
    "Chill Deepvault runs, no mic needed, we teach mechanics as we go.",
    "Need one more for Overclock trios. Anything above Pro is fine.",
    "Coach available for free VOD reviews this week. Ashfall only.",
  ];
  for (const [index, body] of lfgBodies.entries()) {
    await prisma.lFGPost.create({
      data: {
        userId: users[index + 2].id,
        gameId: games[index % games.length].id,
        body,
        needed: 1 + (index % 3),
        minTier: index % 2 === 0 ? "Diamond" : null,
        region: index % 2 === 0 ? "SEA" : "EU West",
        competitive: index % 2 === 0,
        micRequired: index !== 2,
        language: "en",
        createdAt: new Date(Date.now() - index * 5400_000),
      },
    });
  }

  const conversation = await prisma.conversation.create({
    data: {
      isGroup: true,
      title: "Nova Drift — main",
      members: {
        create: [demo, ...users.slice(0, 4)].map((member) => ({ userId: member.id })),
      },
      messages: {
        create: [
          { senderId: users[0].id, body: "Scrim confirmed for 21:00. Same map pool as last week." },
          { senderId: demo.id, body: "Works for me. I'll warm up from 20:30." },
          { senderId: users[2].id, body: "Can we run the new Breach setup on the second map?" },
          { senderId: users[1].id, body: "Yes, but only if we practise the retake first." },
        ],
      },
    },
  });
  await prisma.conversation.create({
    data: {
      members: { create: [{ userId: demo.id }, { userId: users[6].id }] },
      messages: {
        create: [
          { senderId: users[6].id, body: "Saw your clip from Saturday. Want to duo this week?" },
        ],
      },
    },
  });

  const achievements = await Promise.all(
    [
      ["first-broadcast", "First Broadcast", "Complete your first live stream.", "BRONZE", 100],
      ["tournament-rookie", "Tournament Rookie", "Play in your first tournament.", "BRONZE", 150],
      ["champion", "Champion", "Win a tournament.", "GOLD", 1000],
      ["community-builder", "Community Builder", "Grow an active gaming community.", "SILVER", 500],
      ["clip-breakout", "Clip Breakout", "Publish a clip that passes 10,000 views.", "SILVER", 400],
      ["night-shift", "Night Shift", "Play 50 matches after midnight.", "BRONZE", 200],
      ["good-teammate", "Good Teammate", "Receive 25 positive teammate endorsements.", "GOLD", 800],
      ["iron-holder", "Iron Holder", "Hold a point alone for a full round, ten times.", "PLATINUM", 1500],
    ].map(([slug, name, description, tier, xpReward]) =>
      prisma.achievement.create({
        data: {
          slug: slug as string,
          name: name as string,
          description: description as string,
          tier: tier as never,
          xpReward: xpReward as number,
        },
      }),
    ),
  );
  for (const user of [demo, ...users.slice(0, 10)]) {
    for (const achievement of achievements.slice(0, 3 + rnd(4))) {
      await prisma.userAchievement.create({
        data: { userId: user.id, achievementId: achievement.id },
      });
    }
  }

  const liveStream = streams.find((stream) => stream.isLive)!;
  const liveCreator = users.find((user) => user.id === liveStream.userId)!;
  await prisma.notification.createMany({
    data: [
      {
        userId: demo.id,
        kind: "STREAM_LIVE",
        title: `${liveCreator.displayName} is live`,
        body: liveStream.title,
        href: `/watch/${liveStream.slug}`,
      },
      {
        userId: demo.id,
        kind: "TEAM_INVITE",
        title: "Zero Parallax invited you to join",
        body: "They're short an Anchor for the weekend qualifier.",
        href: "/teams/zero-parallax",
      },
      {
        userId: demo.id,
        kind: "TOURNAMENT_REMINDER",
        title: "Ashfall Open Qualifier #3 starts in 30 minutes",
        body: "Your roster is locked. Check in from the tournament page.",
        href: "/tournaments/ashfall-open-qualifier-3",
      },
      {
        userId: demo.id,
        kind: "CLIP_MILESTONE",
        title: "Your clip passed 10K views",
        body: "“Held the point alone for 40 seconds” is trending in Ashfall.",
        href: "/clips",
        readAt: daysAgo(1),
      },
      {
        userId: demo.id,
        kind: "COMMENT_REPLY",
        title: "Mothlight replied to your comment",
        body: "“That lineup only works on the B side though”",
        href: "/clips",
        readAt: daysAgo(2),
      },
    ],
  });

  await prisma.message.updateMany({
    where: { conversationId: conversation.id },
    data: {},
  });

  const counts = {
    users: await prisma.user.count(),
    games: await prisma.game.count(),
    streams: await prisma.stream.count(),
    clips: await prisma.clip.count(),
    teams: await prisma.team.count(),
    tournaments: await prisma.tournament.count(),
    matches: await prisma.tournamentMatch.count(),
    communities: await prisma.community.count(),
  };
  console.log("Seed complete:", counts);
  console.log("Log in as demo@holdpoint.gg / password123");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
